/**
 * OMRO DigitalApp API
 * API used on OMRO Digital Resources
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Type of URL for Namirial KYC
 */
export type KYCUrlType = 'ID' | 'Selfie' | 'Liveness';

export const KYCUrlType = {
    ID: 'ID' as KYCUrlType,
    Selfie: 'Selfie' as KYCUrlType,
    Liveness: 'Liveness' as KYCUrlType
};