/**
 * OMRO DigitalApp API
 * API used on OMRO Digital Resources
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CompanyFunctioningStatus } from './companyFunctioningStatus';
import { NUIDValidationStatus } from './nUIDValidationStatus';
import { FileRepositoryOutputModel } from "~/app/credit-request/models/fileRepositoryOutputModel";
import { DynamicFormOutputModel } from "~/app/credit-request/models/dynamicFormOutputModel";

/**
 * Customer details
 */
export interface CustomerOutputModel {
    /**
     * Customer primary key
     */
    customerId?: string;
    /**
     * Customer national unique ID (CUI)
     */
    customerNUID?: string;
    /**
     * The name of the customer
     */
    customerName?: string;
    /**
     * True if the company KYC was performed
     */
    isKYCDone?: boolean;
    /**
     * Customer NUID validation status against Recom Databse
     */
    nuidValidationStatus?: NUIDValidationStatus;
    /**
     * Registration date from Recom
     */
    registrationDate?: Date;
    /**
     * Registration number from Recom (J)
     */
    registrationNumber?: string;
    /**
     * Text to be displayed above the action button if necessary
     */
    actionText?: string;
    /**
     * Text to be displayed on the action button if necessary
     */
    actionButtonText?: string;
    /**
     * If true, display the action button
     */
    isActionButtonVisible?: boolean;
    /**
     * CAEN Number
     */
    caenNumber?: string;
    /**
     * CAEN Description text
     */
    caenText?: string;
    /**
     * Main address
     */
    mainAddress?: string;
    /**
     * True if the delete button can be used for this customer
     */
    isDeletePermitted?: boolean;
    /**
     * Recom functioning status
     */
    functioningStatus?: CompanyFunctioningStatus;
    /**
     * KYC File Repository
     */
    kycFileRepository?: FileRepositoryOutputModel;
    /**
     * Id of the Dynamic form used for the Customer KYC
     */
    kycDynamicForm?: DynamicFormOutputModel;
}
