/**
 * OMRO DigitalApp API
 * API used on OMRO Digital Resources
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * The status of the role on the user-customer mapping
 */
export type UserCustomerMappingStatus = 'Pending' | 'Approved' | 'NotApproved';

export const UserCustomerMappingStatus = {
    Pending: 'Pending' as UserCustomerMappingStatus,
    Approved: 'Approved' as UserCustomerMappingStatus,
    NotApproved: 'NotApproved' as UserCustomerMappingStatus
};