/**
 * OMRO DigitalApp API
 * API used on OMRO Digital Resources
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Address { 
    readonly deliveryAddress1?: string;
    readonly deliveryAddress2?: string;
    readonly city?: string;
    readonly district?: string;
    readonly postalCode?: string;
}