/**
 * OMRO DigitalApp API
 * API used on OMRO Digital Resources
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface CardDetailsOutputModel { 
    cardId?: string;
    readonly pan?: string;
    readonly holderName?: string;
    readonly companyName?: string;
    readonly cvv2?: string;
    expiryDate?: string;
}