/**
 * OMRO DigitalApp API
 * API used on OMRO Digital Resources
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CardBlockReason } from './cardBlockReason';

export interface CardBlockModel { 
    readonly cardId?: string;
    readonly reason?: CardBlockReason;
}