/**
 * OMRO DigitalApp API
 * API used on OMRO Digital Resources
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { TransactionCategory } from "~/app/accounts/models/api";

/**
 * Payment that is added but not yet confirmed
 */
export interface AddedPaymentOutputModel {
    transactionId?: string;
    valueDate?: Date;
    maxBookedDate?: Date;
    amount?: number;
    amountCurrency?: string;
    currencyPair?: string;
    fxRate?: number;
    currencyCode?: string;
    categoryCode?: TransactionCategory;
    categoryName?: string;
    otherPartyName?: string;
    otherPartyAccount?: string;
    otherPartyBank?: string;
    filboFee?: number;
    interchangeFee?: number;
}
