/**
 * OMRO DigitalApp API
 * API used on OMRO Digital Resources
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Type of transaction
 */
export type TransactionCategory = 'CardPayment' | 'Payment' | 'Incoming' | 'IncomingCardTransfer' | 'FX' | 'Transfer';

export const TransactionCategory = {
    CardPayment: 'CardPayment' as TransactionCategory,
    Payment: 'Payment' as TransactionCategory,
    Incoming: 'Incoming' as TransactionCategory,
    IncomingCardTransfer: 'IncomingCardTransfer' as TransactionCategory,
    FX: 'FX' as TransactionCategory,
    Transfer: 'Transfer' as TransactionCategory
};