/**
 * OMRO DigitalApp API
 * API used on OMRO Digital Resources
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AssociatedCard } from './associatedCard';
import { Chart } from './chart';
import { EligibleCardForAccount } from './eligibleCardForAccount';
import { EligibleTransaction } from './eligibleTransaction';
import { Transaction } from './transaction';

export interface AccountDetailsOutputModel { 
    id?: string;
    iban?: string;
    name?: string;
    bankName?: string;
    bankSwiftCode?: string;
    bankAddress?: string;
    currencyCode?: string;
    workingBalance?: number;
    onlineActualBalance?: number;
    incomes6Months?: number;
    payments6Months?: number;
    eligibleCardMessage?: string;
    color?: string;
    /**
     * List of cards associated with this account
     */
    associatedCards?: Array<AssociatedCard>;
    /**
     * Recent transactions list
     */
    transactions?: Array<Transaction>;
    /**
     * List of transactions that can be initiated from this account
     */
    eligibleTransactions?: Array<EligibleTransaction>;
    /**
     * Account balance in the last 6 months
     */
    chartData?: Array<Chart>;
    eligibleCards?: Array<EligibleCardForAccount>;
}