/**
 * OMRO DigitalApp API
 * API used on OMRO Digital Resources
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Type of alert
 */
export type InitiatedTransactionCategory = 'Payment' | 'FX' | 'Transfer';

export const InitiatedTransactionCategory = {
    Payment: 'Payment' as InitiatedTransactionCategory,
    FX: 'FX' as InitiatedTransactionCategory,
    Transfer: 'Transfer' as InitiatedTransactionCategory
};