/**
 * OMRO DigitalApp API
 * API used on OMRO Digital Resources
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type ApprovalSuccessPicture = 'Zero' | 'High' | 'Low' | 'Medium';

export const ApprovalSuccessPicture = {
    Zero: 'Zero' as ApprovalSuccessPicture,
    High: 'High' as ApprovalSuccessPicture,
    Low: 'Low' as ApprovalSuccessPicture,
    Medium: 'Medium' as ApprovalSuccessPicture
};