/**
 * OMRO DigitalApp API
 * API used on OMRO Digital Resources
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Form field detail
 */
export interface DynamicFormFieldModel { 
    /**
     * Primary Key
     */
    dynamicFormFieldId?: string;
    /**
     * Field value having the folowing format:  Checkbox - True / False (checked/not checked);  Calendar - Date format in yyyy-MM-dd format;
     */
    value?: string;
}