/**
 * OMRO DigitalApp API
 * API used on OMRO Digital Resources
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Downloadable file metadata
 */
export interface FileOutputModel { 
    /**
     * Id of the file
     */
    fileId?: string;
    /**
     * The set id to which the files belongs
     */
    fileSetId?: string;
    /**
     * File name
     */
    fileName?: string;
    /**
     * Mime type of the file
     */
    mimeType?: string;
    /**
     * File extenstion (lowercase containing dot). Eg: .pdf
     */
    fileExtension?: string;
    /**
     * File size in bytes
     */
    fileSizeBytes?: number;
    /**
     * Date when the file was uploaded on Omro or when it was generated by OMRO (UTC)
     */
    generatedDate?: Date;
    /**
     * Id of the user that has generated the file. NULL if the file was generated by OMRO
     */
    generatedByUserId?: string;
    /**
     * Name of the user that has uploaded the file (First name) or OMRO if generated by OMRO
     */
    generatedByUserName?: string;
}