/**
 * OMRO DigitalApp API
 * API used on OMRO Digital Resources
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Information necessary to display the product selection screen
 */
export interface FlowStageProductSelectionOutputModel { 
    /**
     * Id of the generated offer for this request
     */
    productOfferId?: string;
    /**
     * The minimum value of the Amount Slider
     */
    minAllowedAmount?: number;
    /**
     * The maxumum value of the Amount Slider that the user can select. Could be less than the MaxMount
     */
    maxAllowedAmount?: number;
    /**
     * the Periods alowed to be selected
     */
    allowedPeriods?: Array<number>;
    /**
     * Textual information about the proposed offer
     */
    offerDetails?: string;
    /**
     * True if the customer is also an Easy Bill customer
     */
    isSubscribedToEB?: boolean;
    /**
     * The amount that the user should see as proposed when the stage is first loaded.  This can be the RequestedAmount if the MaxAllowedAmount is larger or MaxAllowedAmount if not
     */
    initialProposedAmount?: number;
    /**
     * The period that the UI should select  when the stage is first loaded.
     */
    initialProposedPeriod?: number;
    /**
     * Text to be displayed in the EasyBill section of the screen
     */
    ebMessageDetail?: string;
    /**
     * The interest rated offered to the customer (expressed as a number between 0 and 100)
     */
    offeredInterestRate?: number;
    /**
     * Interest rate to be displayed if the customer is not linked with EB. NULL if the OfferedInterestRate already includes EasyBill discount
     */
    alternateInterestRate?: number;
}