/**
 * OMRO DigitalApp API
 * API used on OMRO Digital Resources
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GenericMainAction } from "./types";

/**
 * The details necessary to display a Generic Stage
 */
export interface FlowStageGenericOutputModel { 
    /**
     * Reference to the Title field (on modal)
     */
    title?: string;
    /**
     * The details of the detail card. Should be displayed if not empty
     */
    details?: string;
    /**
     * The text displayed on the Main Action Button
     */
    mainActionButtonText?: string;
    /**
     * The action to be performed by the Main Action button.  If UserKYC, the User KYC Process should be started.  If FileRepository, the FileRepository linked to the FileRequestFlow should be displayed as a standalone modal.  If NoAction, a modal should be displayed with a title and the text from Details.  If UserApproval, a modal should be displayed with a title and the text from Details and (optionally) a checkbox with the text from AcceptText field.
     */
    mainAction?: GenericMainAction;
    /**
     * If the MainAction is UserApproval and this is not empty/null, the page should display a checkbox at the bottom that must be checked in order to continue
     */
    userApprovalCheckbox?: string;
}