/**
 * OMRO DigitalApp API
 * API used on OMRO Digital Resources
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DashboardModuleType } from './dashboardModuleType';
import { LoansModuleActivityItem } from './loansModuleActivityItem';
import { LoansModuleLoan } from './loansModuleLoan';

/**
 * Module for Loans dashboard card
 */
export interface LoansModule { 
    /**
     * List of loans to be displayed in the module
     */
    loans?: Array<LoansModuleLoan>;
    /**
     * List of activities associates with each loan. The key is the loan ID
     */
    loansActivity?: { [key: string]: Array<LoansModuleActivityItem>; };
    /**
     * The type of the dashboard module
     */
    moduleType?: DashboardModuleType;
}