/**
 * OMRO DigitalApp API
 * API used on OMRO Digital Resources
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Summary of the loan payment during a month
 */
export interface LoansModuleLoanMonthlyPaymentSummary { 
    /**
     * The year of the payment
     */
    year?: number;
    /**
     * The month of the payment
     */
    month?: number;
    /**
     * The full name of the month (localized), first letter capitalized (Ianuarie, Februarie...)
     */
    monthFullName?: string;
    /**
     * The 3 letter name of the month (localized), all caps (IAN, FEB, MAR...)
     */
    monthChartName?: string;
    /**
     * The payment due for the specified month
     */
    paymentDueAmountInMonth?: number;
    /**
     * The payments due for the remaining of the loan duration
     */
    paymentDueAmountRollingTotal?: number;
    /**
     * The amount paid in the month
     */
    paymentRegisteredAmountInMonth?: number;
    /**
     * The difference between the paiments due for the remaining of the loan and the actual paid amount
     */
    paidToPaymentDueAmountRollingTotalDifference?: number;
    /**
     * Total amount of payments up (including) to the month
     */
    paymentRegisteredAmountUpToDate?: number;
    /**
     * True if the specified month is the same as the calendar month.   IsCurrent can be true and one of the IsDueDateInThePast|IsDueDateInTheFuture   can also be true since IsCurrent is looking at the calendar month and the   other 2 properties are looking at the date in the month
     */
    isCurrent?: boolean;
}