/**
 * OMRO DigitalApp API
 * API used on OMRO Digital Resources
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ProductRequestState } from './productRequestState';

/**
 * Details of an product application request
 */
export interface ProductRequestOutputModel { 
    /**
     * Primary key
     */
    productRequestId?: string;
    /**
     * If we differentiate request by product type (eg. standard, line of credit)
     */
    productType?: string;
    /**
     * The customer id
     */
    customerId?: string;
    /**
     * The user that has created the request
     */
    userId?: string;
    /**
     * The date of the application request
     */
    requestDateUTC?: Date;
    /**
     * The date when the request was updated
     */
    lastUpdateDateUTC?: Date;
    /**
     * The title of the request
     */
    title?: string;
    /**
     * The description of the request
     */
    description?: string;
    /**
     * The currency code of the loan (to be used when POST-ing)
     */
    currency?: string;
    /**
     * The UI name of the currency (to be used in UI)
     */
    currencyDislayName?: string;
    /**
     * The amount that the user requested
     */
    requestedAmount?: number;
    /**
     * Duration of the loan as requested by the user
     */
    requestedDuration?: number;
    /**
     * The text entered as purpose for the amount
     */
    purpose?: string;
    /**
     * The amount of each installment based on the Requested Amount or AcceptedAmount (if present)
     */
    installmentAmount?: number;
    /**
     * The amount that the user accepted based on the offer
     */
    acceptedAmount?: number;
    /**
     * The amount that the user accepted based on the offer
     */
    acceptedInterestRate?: number;
    /**
     * Duration of the loan as accepted by the user based on the offer
     */
    acceptedDuration?: number;
    /**
     * The Id of the loan product offered to the customer containing all the details about the loan to be opened  in the Core System
     */
    acceptedProductOfferId?: string;
    /**
     * The current state of the application request
     */
    state?: ProductRequestState;
    /**
     * True if user must perform an action to continue the request flow
     */
    requiresUserInput?: boolean;
}