/**
 * OMRO DigitalApp API
 * API used on OMRO Digital Resources
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DynamicFormOutputModel } from './dynamicFormOutputModel';
import { FileRepositoryOutputModel } from './fileRepositoryOutputModel';
import { FlowStageGenericOutputModel } from './flowStageGenericOutputModel';
import { FlowStageProductSelectionOutputModel } from './flowStageProductSelectionOutputModel';
import { ProductRequestFlowStageDetailsType } from './productRequestFlowStageDetailsType';

/**
 * Detailed information about the current flow stage. The StageType has the same value as the element that contains  the detailed information
 */
export interface ProductRequestFlowStageDetailsOutputModel {
    productRequestFlowStageId: string;
    /**
     * The type of the stage in the request flow. Based on the type, one of the subsequent nodes will have a non-Null value
     */
    stageType?: ProductRequestFlowStageDetailsType;
    /**
     * Present if type is ProductSelection
     */
    productSelection?: FlowStageProductSelectionOutputModel;
    /**
     * Present if type is DynamicForm
     */
    dynamicForm?: DynamicFormOutputModel;
    /**
     * Present if type is FileRepository
     */
    fileRepository?: FileRepositoryOutputModel;
    /**
     * Present if type is Generic
     */
    generic?: FlowStageGenericOutputModel;
}
