/**
 * OMRO DigitalApp API
 * API used on OMRO Digital Resources
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * State of the Product Request
 */
export type ProductRequestState = 'InProgress' | 'CanceledByUser' | 'Rejected' | 'Finished';

export const ProductRequestState = {
    InProgress: 'InProgress' as ProductRequestState,
    CanceledByUser: 'CanceledByUser' as ProductRequestState,
    Rejected: 'Rejected' as ProductRequestState,
    Finished: 'Finished' as ProductRequestState
};