/**
 * OMRO DigitalApp API
 * API used on OMRO Digital Resources
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Posible states of a flow stage
 */
export type ProductRequestFlowStageState = 'Finished' | 'InProgress' | 'NotStarted';

export const ProductRequestFlowStageState = {
    Finished: 'Finished' as ProductRequestFlowStageState,
    InProgress: 'InProgress' as ProductRequestFlowStageState,
    NotStarted: 'NotStarted' as ProductRequestFlowStageState
};