/**
 * OMRO DigitalApp API
 * API used on OMRO Digital Resources
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * The type of Product Request Flow Stage used to draw the interface
 */
export type ProductRequestFlowStageDetailsType = 'DynamicForm' | 'ProductSelection' | 'Generic' | 'FileRepository';

export const ProductRequestFlowStageDetailsType = {
    DynamicForm: 'DynamicForm' as ProductRequestFlowStageDetailsType,
    ProductSelection: 'ProductSelection' as ProductRequestFlowStageDetailsType,
    Generic: 'Generic' as ProductRequestFlowStageDetailsType,
    FileRepository: 'FileRepository' as ProductRequestFlowStageDetailsType
};