/**
 * OMRO DigitalApp API
 * API used on OMRO Digital Resources
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * New product request data. Allowed values are provided by the available products API
 */
export interface ProductRequestModel { 
    /**
     * The currency of the loan
     */
    currency: string;
    /**
     * The amount that the user requested
     */
    requestedAmount: number;
    /**
     * Duration of the loan as requested by the user
     */
    requestedDuration: number;
    /**
     * The text entered as purpose for the amount
     */
    purpose: string;
    /**
     * If we differentiate request by product type (eg. standard, line of credit). Default value: \"standard\"
     */
    productType: string;
}