/**
 * OMRO DigitalApp API
 * API used on OMRO Digital Resources
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ProductRequestFlowStageDetailsOutputModel } from './productRequestFlowStageDetailsOutputModel';
import { ProductRequestFlowStageState } from './productRequestFlowStageState';

/**
 * Describes a stage for a Product Application Request Flow
 */
export interface ProductRequestFlowStageOutputModel { 
    /**
     * The title of the stage displayed in the Overview and in the Details. Localized
     */
    title?: string;
    /**
     * The text details of the stage to be used only in the overview (as a summary of the stage or as call to action text). Localized
     */
    details?: string;
    /**
     * The text to be displayed on the action button. If empty, the button should not be displyed
     */
    actionButtonText?: string;
    /**
     * The state of the stage. Only one InProgress stage can exist and only that stage has StageDetails
     */
    state?: ProductRequestFlowStageState;
    /**
     * True if the stage waits for the customer to do some actions,  False if the stage waits for OMRO to do some action.
     */
    requiresUserInput?: boolean;
    /**
     * Contains the details about the stage and action information to be done by the customer, if needed  NULL if the State is not InProgress
     */
    stageDetails?: ProductRequestFlowStageDetailsOutputModel;
}