/**
 * OMRO DigitalApp API
 * API used on OMRO Digital Resources
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Type of alert
 */
export type AlertType = 'Informational' | 'Warning' | 'Success' | 'Error';

export const AlertType = {
    Informational: 'Informational' as AlertType,
    Warning: 'Warning' as AlertType,
    Success: 'Success' as AlertType,
    Error: 'Error' as AlertType
};