/**
 * OMRO DigitalApp API
 * API used on OMRO Digital Resources
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AlertType } from './alertType';
import { NotificationCallToActionLocationEnum } from './notificationCallToActionLocationEnum';
import { NotificationCallToActionTypeEnum } from './notificationCallToActionTypeEnum';
import { NotificationTypeEnum } from './notificationTypeEnum';

export interface FilboNotificationsOutputModel {
    /**
     * Unique if of the notification
     */
    filboNotificationId?: string;
    /**
     * If not null, the notification targets this customer id
     */
    customerId?: string;
    /**
     * Date when the notification was created
     */
    generatedDateUtc?: Date;
    /**
     * Title of the notification part
     */
    title?: string;
    /**
     * Body of the notification part
     */
    body?: string;
    /**
     * Serialized Dictionary(string,string) of values in JSON format. This always includes FilboNotificationId value
     */
    serializedDictionary?: string;
    /**
     * Priority between 1 and 10, 1 having the highest priority
     */
    priority?: number;
    /**
     * Type of UI to be used
     */
    notificationType?: NotificationTypeEnum;
    /**
     * Used to set the color for toast notifications
     */
    alertType?: AlertType;
    /**
     * If zero, the alert should not close automatically. If greater than zero, the alert is hidden after this many seconds
     */
    autoCloseInterval?: number;
    /**
     * What the app should do if the notification is taped or a button is pressed (modal)
     */
    callToActionType?: NotificationCallToActionTypeEnum;
    /**
     * Where the app should navigate if the CallToActionType is Navigate
     */
    callToActionLocation?: NotificationCallToActionLocationEnum;
    /**
     * Id of a specific target. Depends on the location. When used, the app should use case insensitive comparision
     */
    callToActionReference?: string;
}
