/**
 * OMRO DigitalApp API
 * API used on OMRO Digital Resources
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Type of URL for Namirial KYC
 */
export type NotificationTypeEnum = 'Toast' | 'Modal' | 'DismissableModal' | 'None';

export const NotificationTypeEnum = {
    Toast: 'Toast' as NotificationTypeEnum,
    Modal: 'Modal' as NotificationTypeEnum,
    DismissableModal: 'DismissableModal' as NotificationTypeEnum,
    None: 'None' as NotificationTypeEnum
};