/**
 * OMRO DigitalApp API
 * API used on OMRO Digital Resources
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Where the app should navigate if the CallToActionType is Navigate
 */
export type NotificationCallToActionLocationEnum = 'Unspecified' | 'ProductApplicationRequest' | 'UserProfile' | 'CompanySetup' | 'HomePage';

export const NotificationCallToActionLocationEnum = {
    Unspecified: 'Unspecified' as NotificationCallToActionLocationEnum,
    ProductApplicationRequest: 'ProductApplicationRequest' as NotificationCallToActionLocationEnum,
    UserProfile: 'UserProfile' as NotificationCallToActionLocationEnum,
    CompanySetup: 'CompanySetup' as NotificationCallToActionLocationEnum,
    HomePage: 'HomePage' as NotificationCallToActionLocationEnum
};
