/**
 * OMRO DigitalApp API
 * API used on OMRO Digital Resources
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * What the app should do if the notification is taped or a button is pressed (modal)
 */
export type NotificationCallToActionTypeEnum = 'DoNothing' | 'Navigate';

export const NotificationCallToActionTypeEnum = {
    DoNothing: 'DoNothing' as NotificationCallToActionTypeEnum,
    Navigate: 'Navigate' as NotificationCallToActionTypeEnum
};